# Generated by Django 3.0 on 2021-02-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bike'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
            preserve_default=False,
        ),
    ]
