# Generated by Django 3.0 on 2021-02-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='image',
            field=models.CharField(default='https://i.imgur.com/DY6k0Re.jpg', max_length=300),
            preserve_default=False,
        ),
    ]
